package gjclog

import (
	"encoding/json"
	"strings"
	"time"
)

// Record is a normalized gjc session record.
type Record struct {
	SessionID  string
	MessageID  string
	ParentID   string
	Timestamp  time.Time
	RecordType string // "user" | "assistant" | "tool_result" | "tool_call"
	CWD        string
	Title      string
	Model      string
	Provider   string
	Content    string
	// Thinking holds assistant reasoning-block text, kept separate from
	// Content: real data shows most assistant messages carry a thinking block
	// with no text block, so folding them together would make Content pure
	// reasoning rather than what the assistant actually said.
	Thinking   string
	ToolName   string
	ToolCallID string
	// ToolArgs holds the raw arguments JSON of a toolCall content block; set
	// only on RecordType == "tool_call" records.
	ToolArgs string
	IsError  bool
	// Attribution is gjc's equivalent of Claude Code's prompt_source: it
	// distinguishes a human-typed user turn from one gjc generated itself.
	// Observed values are "user" (human typed) and "agent" (generated by gjc
	// for its own task work), but the set is not known to be closed, so
	// downstream must treat any unrecognized value as "not proven human"
	// rather than assuming it means human. Empty when the field is absent
	// from the record - an absent field is not evidence of either value.
	Attribution string

	// Usage and cost populate only on assistant records: gjc embeds them on
	// the assistant message itself, unlike codexlog's separate usage records.
	InputTokens      *int
	OutputTokens     *int
	CacheReadTokens  *int
	CacheWriteTokens *int
	TotalTokens      *int
	CostUSD          *float64
	DurationMS       *float64
	TTFTMS           *float64

	Raw json.RawMessage
}

// TokenLogRecord is one line of a project-local token-log.jsonl. Unlike
// Record, it carries no cost: gjc's token log has no rate table attached.
type TokenLogRecord struct {
	SubagentID  string
	Agent       string
	Turn        int
	At          time.Time
	Input       int
	Output      int
	CacheRead   int
	CacheWrite  int
	TotalTokens int
	Model       string
	Raw         json.RawMessage
}

// scanState carries per-file mutable state during a scan pass. The header
// line (type "session") is the only source of cwd and title; gjc has no
// per-turn equivalent of Codex's turn_context.
type scanState struct {
	sessionID string
	cwd       string
	title     string
}

// --- raw JSON structs ---

// headerLine is the first line of a gjc session file.
type headerLine struct {
	Type  string `json:"type"`
	ID    string `json:"id"`
	CWD   string `json:"cwd"`
	Title string `json:"title"`
}

type rawLine struct {
	Type      string          `json:"type"`
	ID        string          `json:"id"`
	ParentID  string          `json:"parentId"`
	Timestamp string          `json:"timestamp"`
	Message   json.RawMessage `json:"message"`
}

type messagePayload struct {
	Role        string          `json:"role"`
	Content     json.RawMessage `json:"content"`
	Provider    string          `json:"provider"`
	Model       string          `json:"model"`
	Duration    *float64        `json:"duration"`
	TTFT        *float64        `json:"ttft"`
	Usage       *usagePayload   `json:"usage"`
	ToolName    string          `json:"toolName"`
	ToolCallID  string          `json:"toolCallId"`
	IsError     bool            `json:"isError"`
	Attribution string          `json:"attribution"`
}

type usagePayload struct {
	Input       int          `json:"input"`
	Output      int          `json:"output"`
	CacheRead   int          `json:"cacheRead"`
	CacheWrite  int          `json:"cacheWrite"`
	TotalTokens int          `json:"totalTokens"`
	Cost        *costPayload `json:"cost"`
}

type costPayload struct {
	Total float64 `json:"total"`
}

type contentItem struct {
	Type      string          `json:"type"`
	Text      string          `json:"text"`
	Thinking  string          `json:"thinking"`
	ID        string          `json:"id"`
	Name      string          `json:"name"`
	Arguments json.RawMessage `json:"arguments"`
}

// toolCallBlock is a normalized toolCall content block extracted from an
// assistant message.
type toolCallBlock struct {
	ID        string
	Name      string
	Arguments string
}

type tokenLogLine struct {
	SubagentID  string `json:"subagentId"`
	Agent       string `json:"agent"`
	Turn        int    `json:"turn"`
	At          string `json:"at"`
	Input       int    `json:"input"`
	Output      int    `json:"output"`
	CacheRead   int    `json:"cacheRead"`
	CacheWrite  int    `json:"cacheWrite"`
	TotalTokens int    `json:"totalTokens"`
	Model       string `json:"model"`
}

// --- parsers ---

// parseLine parses a single line of a gjc session file, returning zero or
// more records. The header line (type "session") updates state and returns
// nil. Non-message state-only or ignored lines (model_change,
// thinking_level_change, configured_model_chain, custom, custom_message,
// session_init, compaction) also return nil. A message line normally yields
// one record, but an assistant message with toolCall content blocks yields
// its own record plus one additional "tool_call" record per block, mirroring
// codexlog's function_call handling.
func parseLine(line []byte, state *scanState) []*Record {
	var probe struct {
		Type string `json:"type"`
	}
	if err := json.Unmarshal(line, &probe); err != nil {
		return nil
	}

	switch probe.Type {
	case "session":
		var h headerLine
		if err := json.Unmarshal(line, &h); err == nil {
			// Only overwrite inherited state with non-empty header values, so a
			// header re-scanned without full fields (or a resumed scan seeded
			// from prior Metadata) cannot clobber what is already known.
			if state.sessionID == "" && h.ID != "" {
				state.sessionID = h.ID
			}
			if h.CWD != "" {
				state.cwd = h.CWD
			}
			if h.Title != "" {
				state.title = h.Title
			}
		}
		return nil

	case "message":
		var rl rawLine
		if err := json.Unmarshal(line, &rl); err != nil {
			return nil
		}
		var mp messagePayload
		if err := json.Unmarshal(rl.Message, &mp); err != nil {
			return nil
		}
		recordType := roleToRecordType(mp.Role)
		if recordType == "" {
			return nil
		}

		text, thinking, toolCalls := extractContent(mp.Content)

		rec := &Record{
			SessionID:   state.sessionID,
			MessageID:   rl.ID,
			ParentID:    rl.ParentID,
			Timestamp:   parseTimestamp(rl.Timestamp),
			RecordType:  recordType,
			CWD:         state.cwd,
			Title:       state.title,
			Content:     text,
			Attribution: mp.Attribution,
			Raw:         line,
		}

		records := []*Record{rec}

		switch recordType {
		case "assistant":
			rec.Model = mp.Model
			rec.Provider = mp.Provider
			rec.DurationMS = mp.Duration
			rec.TTFTMS = mp.TTFT
			rec.Thinking = thinking
			if mp.Usage != nil {
				in, out := mp.Usage.Input, mp.Usage.Output
				cacheRead, cacheWrite, total := mp.Usage.CacheRead, mp.Usage.CacheWrite, mp.Usage.TotalTokens
				rec.InputTokens = &in
				rec.OutputTokens = &out
				rec.CacheReadTokens = &cacheRead
				rec.CacheWriteTokens = &cacheWrite
				rec.TotalTokens = &total
				if mp.Usage.Cost != nil {
					cost := mp.Usage.Cost.Total
					rec.CostUSD = &cost
				}
			}
			// toolCall blocks only occur in assistant messages (gjc puts tool
			// invocations there, never in user/toolResult content); scoping the
			// loop here keeps a stray "toolCall"-typed block elsewhere from
			// producing a sparse, context-free tool_call record.
			for _, tc := range toolCalls {
				records = append(records, &Record{
					SessionID:  state.sessionID,
					MessageID:  rl.ID,
					ParentID:   rl.ParentID,
					Timestamp:  rec.Timestamp,
					RecordType: "tool_call",
					CWD:        state.cwd,
					Title:      state.title,
					Model:      rec.Model,
					Provider:   rec.Provider,
					ToolName:   tc.Name,
					ToolCallID: tc.ID,
					ToolArgs:   tc.Arguments,
					Raw:        line,
				})
			}
		case "tool_result":
			rec.ToolName = mp.ToolName
			rec.ToolCallID = mp.ToolCallID
			rec.IsError = mp.IsError
		}

		return records

	default:
		return nil
	}
}

// parseTokenLogLine parses a single line of a project-local token-log.jsonl.
// Returns nil for malformed lines, and for lines that parse but carry no real
// entry (a JSON `null` line, or an empty object) - both unmarshal cleanly
// into a zero-value struct, so a minimal validity gate (a subagent id or a
// parseable timestamp) keeps those from becoming a hollow record.
func parseTokenLogLine(line []byte) *TokenLogRecord {
	var tl tokenLogLine
	if err := json.Unmarshal(line, &tl); err != nil {
		return nil
	}
	if tl.SubagentID == "" && tl.At == "" {
		return nil
	}
	return &TokenLogRecord{
		SubagentID:  tl.SubagentID,
		Agent:       tl.Agent,
		Turn:        tl.Turn,
		At:          parseTimestamp(tl.At),
		Input:       tl.Input,
		Output:      tl.Output,
		CacheRead:   tl.CacheRead,
		CacheWrite:  tl.CacheWrite,
		TotalTokens: tl.TotalTokens,
		Model:       tl.Model,
		Raw:         line,
	}
}

// --- helpers ---

func roleToRecordType(role string) string {
	switch role {
	case "assistant":
		return "assistant"
	case "toolResult":
		return "tool_result"
	case "user":
		return "user"
	}
	return ""
}

func parseTimestamp(s string) time.Time {
	if s == "" {
		return time.Time{}
	}
	t, err := time.Parse(time.RFC3339Nano, s)
	if err != nil {
		t, _ = time.Parse("2006-01-02T15:04:05.000Z", s)
	}
	return t
}

// extractContent splits a message content field into plain reply text,
// reasoning text, and toolCall blocks. Handles: array of typed blocks (only
// "text" contributes to text, only "thinking" to thinking - gating on Type
// rather than field presence future-proofs against other block types growing
// a "text"-shaped field), plain string, or null.
func extractContent(raw json.RawMessage) (text, thinking string, toolCalls []toolCallBlock) {
	if len(raw) == 0 {
		return "", "", nil
	}
	var items []contentItem
	if err := json.Unmarshal(raw, &items); err == nil {
		var textParts, thinkingParts []string
		for _, item := range items {
			switch item.Type {
			case "text":
				if item.Text != "" {
					textParts = append(textParts, item.Text)
				}
			case "thinking":
				if item.Thinking != "" {
					thinkingParts = append(thinkingParts, item.Thinking)
				}
			case "toolCall":
				args := ""
				if item.Arguments != nil {
					args = string(item.Arguments)
				}
				toolCalls = append(toolCalls, toolCallBlock{ID: item.ID, Name: item.Name, Arguments: args})
			}
		}
		return strings.Join(textParts, "\n"), strings.Join(thinkingParts, "\n"), toolCalls
	}
	var s string
	if err := json.Unmarshal(raw, &s); err == nil {
		return s, "", nil
	}
	return "", "", nil
}
